apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: r2a5cazpi-java-springboot
  janus-idp.io/tekton: r2a5cazpi-java-springboot
  backstage.io/kubernetes-id: r2a5cazpi-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r2a5cazpi-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
